//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTracke
    {
        public int id { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<int> NGOId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> FoodItemsId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> accept_time { get; set; }
        public Nullable<System.DateTime> collecting_time { get; set; }
        public string status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual NGO NGO { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
